"""Defaults and normalization for GitflowConfig YAML (authoritative policy)."""

from __future__ import annotations

from typing import Any

DEFAULT_GITFLOW_OPTIONS: dict[str, Any] = {
    "require_ci": False,
    "branch_naming": False,
    "with_templates": False,
    "init_empty": False,
    "workspace": "",
}

DEFAULT_BRANCH_NAMING: dict[str, Any] = {
    "mode": "standard",
    "allowed_prefixes": ["feature", "fix", "hotfix", "release", "chore"],
    "exceptions": ["dependabot/*"],
    "slug_pattern": r"^[a-zA-Z0-9][a-zA-Z0-9._-]+$",
    "strict_feature_pattern": (
        r"^feature/INIT-[A-Z]+-[A-Z0-9]+-[0-9]{3}-[a-z0-9][a-z0-9._-]+$"
    ),
    "block_sources": ["main", "develop"],
}

DEFAULT_BRANCH_PROTECTION: dict[str, Any] = {
    "required_approving_review_count": 1,
    "dismiss_stale_reviews": True,
    "require_code_owner_reviews": False,
    "enforce_admins": True,
    "allow_force_pushes": False,
    "allow_deletions": False,
}

DEFAULT_MERGE_POLICY: dict[str, Any] = {
    "develop": {
        "allowed_head_prefixes": ["feature", "fix", "chore", "hotfix"],
        "block_sources": ["main", "develop"],
    },
    "main": {
        "allowed_head_refs": ["develop"],
        "allowed_head_prefixes": ["release", "hotfix"],
    },
}


def _merge_dict(base: dict[str, Any], override: dict[str, Any] | None) -> dict[str, Any]:
    out = dict(base)
    if override:
        out.update(override)
    return out


def normalize_gitflow_policy(cfg: dict[str, Any]) -> dict[str, Any]:
    """Fill gitflow policy sections with defaults; YAML is the only source of truth."""
    options = _merge_dict(DEFAULT_GITFLOW_OPTIONS, cfg.get("options"))
    branch_naming = _merge_dict(DEFAULT_BRANCH_NAMING, cfg.get("branch_naming"))
    protection_raw = cfg.get("protection") or {}
    protection = {
        "develop": _merge_dict(DEFAULT_BRANCH_PROTECTION, protection_raw.get("develop")),
        "main": _merge_dict(DEFAULT_BRANCH_PROTECTION, protection_raw.get("main")),
    }
    merge_raw = cfg.get("merge_policy") or {}
    merge_policy = {
        "develop": _merge_dict(DEFAULT_MERGE_POLICY["develop"], merge_raw.get("develop")),
        "main": _merge_dict(DEFAULT_MERGE_POLICY["main"], merge_raw.get("main")),
    }
    return {
        "options": options,
        "branch_naming": branch_naming,
        "protection": protection,
        "merge_policy": merge_policy,
    }


def branch_naming_ref_excludes(branch_naming: dict[str, Any]) -> list[str]:
    """GitHub ruleset ref excludes derived from branch_naming policy."""
    excludes = ["refs/heads/main", "refs/heads/develop"]
    for prefix in branch_naming.get("allowed_prefixes") or []:
        excludes.append(f"refs/heads/{prefix}/**")
    for pattern in branch_naming.get("exceptions") or []:
        excludes.append(f"refs/heads/{pattern}")
    return excludes


def render_policy_branch_name_workflow(branch_naming: dict[str, Any]) -> str:
    prefixes = branch_naming.get("allowed_prefixes") or []
    prefix_alt = "|".join(prefixes)
    block_sources = "|".join(branch_naming.get("block_sources") or ["main", "develop"])
    mode = branch_naming.get("mode", "standard")
    strict_pattern = branch_naming.get(
        "strict_feature_pattern", DEFAULT_BRANCH_NAMING["strict_feature_pattern"]
    )
    prefix_list = ", ".join(prefixes)

    return f"""# Generated by launchpad setup-gitflow from gitflow YAML (branch_naming).
# Do not edit by hand — change config/gitflow-*.yaml and re-run setup-gitflow.

name: policy-branch-name

on:
  pull_request:
    branches: [develop]

jobs:
  policy-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: validate head branch name
        env:
          HEAD: ${{{{ github.head_ref }}}}
          NAMING_MODE: {mode}
        run: |
          set -euo pipefail

          case "$HEAD" in
            {block_sources})
              echo "Cannot open PR to develop from $HEAD"
              exit 1
              ;;
          esac

          ALLOWED_REGEX='^({prefix_alt})/[a-zA-Z0-9][a-zA-Z0-9._-]+$'
          if [[ ! "$HEAD" =~ $ALLOWED_REGEX ]]; then
            echo "Branch name must match: <prefix>/<slug>"
            echo "  Allowed prefixes: {prefix_list}"
            echo "  Got: $HEAD"
            exit 1
          fi

          if [[ "$NAMING_MODE" == "strict" ]]; then
            case "$HEAD" in
              feature/*)
                if [[ ! "$HEAD" =~ {strict_pattern} ]]; then
                  echo "Strict mode: feature branches must match strict_feature_pattern in gitflow YAML"
                  echo "  Got: $HEAD"
                  exit 1
                fi
                ;;
            esac
          fi

          echo "OK: $HEAD"
"""


def render_policy_merge_source_workflow(merge_policy: dict[str, Any]) -> str:
    main_policy = merge_policy.get("main") or DEFAULT_MERGE_POLICY["main"]
    allowed_refs = list(main_policy.get("allowed_head_refs") or [])
    allowed_prefixes = list(main_policy.get("allowed_head_prefixes") or [])

    case_lines: list[str] = []
    for ref in allowed_refs:
        case_lines.append(f'            {ref}) echo "OK: {ref} → main"; exit 0 ;;')
    for prefix in allowed_prefixes:
        case_lines.append(f'            {prefix}/*) echo "OK: {prefix} → main"; exit 0 ;;')
    cases = "\n".join(case_lines)
    allowed_desc = ", ".join([*allowed_refs, *[f"{p}/*" for p in allowed_prefixes]])

    return f"""# Generated by launchpad setup-gitflow from gitflow YAML (merge_policy.main).
# Do not edit by hand — change config/gitflow-*.yaml and re-run setup-gitflow.

name: policy-merge-source

on:
  pull_request:
    branches: [main]

jobs:
  policy-merge-source:
    runs-on: ubuntu-latest
    steps:
      - name: main only from allowed sources (gitflow merge_policy)
        env:
          HEAD: ${{{{ github.head_ref }}}}
        run: |
          case "$HEAD" in
{cases}
            *)
              echo "PR to main must be from {allowed_desc} — not: $HEAD"
              exit 1
              ;;
          esac
"""
