apiVersion: launchpad/v1
kind: GitflowConfig

org: kd_diet_coke

teams:
  release_managers: release-managers
  pm: pm-team
  backend: backend-devs
  frontend: frontend-devs
  platform: platform-devs

profiles:
  backend: backend
  frontend: frontend
  platform: platform

repos:
  diet_coke-api:
    profile: backend
  diet_coke-bff:
    profile: frontend
  diet_coke-registry:
    profile: backend

options:
  require_ci: false
  branch_naming: true
  with_templates: true
  init_empty: true
  workspace: ..

branch_naming:
  mode: standard
  allowed_prefixes:
    - feature
    - fix
    - hotfix
    - release
    - chore
  exceptions:
    - dependabot/*
  block_sources:
    - main
    - develop

protection:
  develop:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    enforce_admins: true
  main:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    enforce_admins: true

merge_policy:
  develop:
    allowed_head_prefixes:
      - feature
      - fix
      - chore
      - hotfix
    block_sources:
      - main
      - develop
  main:
    allowed_head_refs:
      - develop
    allowed_head_prefixes:
      - release
      - hotfix
