apiVersion: launchpad/v1
kind: PlatformManifest

org: kd_diet_coke
name: diet_coke platform baseline

setup:
  - id: repos
    command: bootstrap-org
    config: scripts/config/org-kd_diet_coke.yaml

  - id: teams
    command: bootstrap-teams
    config: scripts/config/org-kd_diet_coke.yaml

  - id: gitflow
    command: setup-gitflow
    config: scripts/config/gitflow-kd_diet_coke.yaml

  - id: board
    command: bootstrap-project
    config: scripts/config/project-kd_diet_coke.yaml

verify:
  config: scripts/config/verify-platform-kd_diet_coke.yaml
