"""Patch ~/.config/launchpad client registry from OnboardingSpec."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from launchpad.clients import CLIENTS_FILE, CONFIG_DIR, ENV_D_DIR
from launchpad.onboarding.errors import OnboardingError


def _load_registry() -> dict[str, Any]:
    if not CLIENTS_FILE.is_file():
        return {"clients": []}
    with CLIENTS_FILE.open(encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise OnboardingError(f"expected mapping in {CLIENTS_FILE}")
    if "clients" not in data:
        data["clients"] = []
    return data


def patch_clients_registry(
    *,
    client_id: str,
    meta_path: Path,
    forge_type: str,
    set_default: bool = False,
) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    data = _load_registry()
    clients = data.get("clients") or []
    if not isinstance(clients, list):
        raise OnboardingError("clients must be a list")

    entry = {
        "id": client_id,
        "path": str(meta_path),
        "forge": forge_type,
    }
    updated = False
    for idx, item in enumerate(clients):
        if isinstance(item, dict) and item.get("id") == client_id:
            clients[idx] = entry
            updated = True
            break
    if not updated:
        clients.append(entry)
    data["clients"] = clients

    if set_default:
        data["default"] = client_id

    with CLIENTS_FILE.open("w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False, default_flow_style=False)


def write_secrets_stub(*, client_id: str, forge_type: str, overwrite: bool = False) -> Path:
    ENV_D_DIR.mkdir(parents=True, exist_ok=True)
    path = ENV_D_DIR / f"{client_id}.env"
    if path.is_file() and not overwrite:
        return path

    lines = [
        f"# {client_id} factory secrets — chmod 600",
        f"# Generated by launchpad onboard apply",
        "",
    ]
    if forge_type == "gitlab":
        lines.append("GITLAB_TOKEN=glpat-REPLACE_ME")
        lines.append("# GITHUB_TOKEN=  # not used for GitLab forge")
    else:
        lines.append("GITHUB_TOKEN=github_pat_REPLACE_ME")
        lines.append("# GITLAB_TOKEN=  # GitLab forge only")
    lines.extend(
        [
            "",
            f"# LAUNCHPAD_TENANT_ROOT={Path('~/Workspace/handson').expanduser() / client_id / f'{client_id}-meta'}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(0o600)
    return path
