"""Generate tenant template overrides from kit + OnboardingSpec."""

from __future__ import annotations

from pathlib import Path

from launchpad.onboarding.context import OnboardingContext
from launchpad.paths import kit_root

_LAUNCHPAD_PLAYBOOK = "https://github.com/drivestream-lab/launchpad/tree/main/playbook"
_LAUNCHPAD_BLOB = "https://github.com/drivestream-lab/launchpad/blob/main/playbook"


def _read_kit(rel: str) -> str:
    path = kit_root() / "templates" / rel
    if not path.is_file():
        raise FileNotFoundError(f"kit template missing: {path}")
    return path.read_text(encoding="utf-8")


def _codeowners(ctx: OnboardingContext, role: str) -> str:
    team = ctx.org_at_team(role)
    return f"""# {role} profile — {ctx.display_name}

/docs/specification/ {team}
/src/ {team}
/tests/ {team}
* {team}
"""


def _harness_pin(ctx: OnboardingContext, profile: str, rules_key: str) -> str:
    rules = ctx.spec["rules"][rules_key]
    return f"""# Harness pin — do not edit refs without platform approval.
# Generated by: launchpad sync-harness --repo {{{{REPO}}}} --apply
# Docs: https://github.com/drivestream-lab/launchpad/blob/main/playbook/harness-pins.md

profile: {profile}

rules:
  repo: {rules['repo']}
  ref: {{{{RULES_REF}}}}

agent_skills:
  repo: {ctx.spec['agent_skills']['repo']}
  ref: {{{{AGENT_SKILLS_REF}}}}
  skills:
{{{{AGENT_SKILLS_LIST}}}}
"""


def _agents_process_section(ctx: OnboardingContext, rules_repo: str, rules_label: str) -> str:
    meta = ctx.meta_playbook_url
    board = ctx.board_url
    return f"""## {ctx.display_name} process ({ctx.org})

Process SSOT: [launchpad playbook]({_LAUNCHPAD_PLAYBOOK}) · Tenant deltas: [{ctx.meta_repo} playbook]({meta})

| Topic | Link |
|-------|------|
| SDD workflow | [launchpad sdd-workflow]({_LAUNCHPAD_BLOB}/sdd-workflow.md) |
| Harness pins | [launchpad harness-pins]({_LAUNCHPAD_BLOB}/harness-pins.md) |
| PM ↔ dev handoff | [launchpad pm-dev-handoff]({_LAUNCHPAD_BLOB}/pm-dev-handoff.md) |
| Program board | [{ctx.spec['project']['name']}]({board}) |

**Constitution:** [{rules_label}](https://github.com/{rules_repo}) @ {{{{RULES_PIN}}}}

**PRs:** use `.github/pull_request_template.md` — Initiative, Spec path, Verify command.
"""


def _agents_python(ctx: OnboardingContext) -> str:
    rules = ctx.spec["rules"]["python"]["repo"]
    text = _read_kit("AGENTS.python.md")
    text = text.replace(
        "Shared rules: **`.cursor/rules/*.mdc`** (git submodule `your-org/service-rules`, pinned at **{{RULES_PIN}}**).",
        f"Shared rules: **`.cursor/rules/*.mdc`** (git submodule [{rules.split('/')[-1]}](https://github.com/{rules}), pinned at **{{{{RULES_PIN}}}}**).",
    )
    old_process = """## Process

Playbook SSOT: **launchpad** `playbook/` (pinned from tenant `<client>-meta`).

| Topic | Where |
|-------|--------|
| SDD workflow | launchpad `playbook/sdd-workflow.md` |
| Harness pins | launchpad `playbook/harness-pins.md` |
| PM ↔ dev handoff | launchpad `playbook/pm-dev-handoff.md` |
| Program board | Your forge engineering board (tenant wiki) |

**PRs:** use `.github/pull_request_template.md` — Initiative, Spec path, Verify command."""
    text = text.replace(old_process, _agents_process_section(ctx, rules, rules.split("/")[-1]))
    return text


def _agents_frontend(ctx: OnboardingContext) -> str:
    rules = ctx.spec["rules"]["frontend"]["repo"]
    text = _read_kit("AGENTS.frontend.md")
    text = text.replace(
        "Shared rules: **`.cursor/rules/*.mdc`** (git submodule `your-org/frontend-rules`, pinned at **{{RULES_PIN}}**).",
        f"Shared rules: **`.cursor/rules/*.mdc`** (git submodule [nextjs-bff-rules](https://github.com/{rules}), pinned at **{{{{RULES_PIN}}}}**).",
    )
    old_process = """## Process

Playbook SSOT: **launchpad** `playbook/` (tenant `<client>-meta` holds product deltas only).

| Topic | Where |
|-------|--------|
| SDD workflow | launchpad `playbook/sdd-workflow.md` |
| Harness pins | launchpad `playbook/harness-pins.md` |
| PM ↔ dev handoff | launchpad `playbook/pm-dev-handoff.md` |
| Program board | Your forge engineering board (tenant wiki) |

**PRs:** use `.github/pull_request_template.md` — Initiative, Spec path, Verify command."""
    text = text.replace(old_process, _agents_process_section(ctx, rules, "nextjs-bff-rules"))
    return text


def _templates_readme(ctx: OnboardingContext) -> str:
    return f"""# Tenant template overrides ({ctx.org})

**Kit defaults:** `launchpad/templates/` (installed with pipx / editable install).

**This folder:** {ctx.display_name}-specific overrides only. `launchpad sync-harness` and `setup-gitflow --with-templates` resolve each file here first, then fall back to the kit.

Do **not** store constitution (`.mdc` rules) here — those live in private `{ctx.org}/*-rules` repos.

Do **not** duplicate kit-generic files unchanged — delete the override and use kit fallback.

Generated by `launchpad onboard apply` from `onboarding.yaml`.
"""


def _pr_template(ctx: OnboardingContext) -> str:
    return f"""## PR type

- [ ] **Meta / playbook** ({ctx.meta_repo} — PM or platform merges)
- [ ] **Spec handoff** (PM authors, dev merges — label `spec`, no product code)
- [ ] **Implementation** (`feature/*` or `chore/*` — dev merges)

## Traceability

- Initiative: INIT-___
- Issue: #
- **Base branch:** develop

## Verify

```text
(paste command + result)
```
"""


def all_template_renders(ctx: OnboardingContext) -> dict[str, str]:
    if not ctx.spec["overrides"]["generate_templates"]:
        return {"templates/README.md": _templates_readme(ctx)}

    out: dict[str, str] = {
        "templates/README.md": _templates_readme(ctx),
        "templates/AGENTS.python.md": _agents_python(ctx),
        "templates/CODEOWNERS.backend": _codeowners(ctx, "backend"),
        "templates/CODEOWNERS.platform": _codeowners(ctx, "platform"),
        "templates/harness-pin.yaml": _harness_pin(ctx, "python-backend", "python"),
        "templates/pull_request_template.md": _pr_template(ctx),
    }
    if any(r["profile"] == "frontend" for r in ctx.spec["repos"]):
        out["templates/AGENTS.frontend.md"] = _agents_frontend(ctx)
        out["templates/CODEOWNERS.frontend"] = _codeowners(ctx, "frontend")
        out["templates/harness-pin.frontend.yaml"] = _harness_pin(ctx, "frontend", "frontend")
    if any(r["profile"] == "data_platform" for r in ctx.spec["repos"]):
        rules_key = "data_platform" if "data_platform" in ctx.spec["rules"] else "python"
        out["templates/AGENTS.data-platform.md"] = _agents_python(ctx)
        out["templates/CODEOWNERS.data-platform"] = _codeowners(ctx, "data_platform")
        out["templates/harness-pin.data-platform.yaml"] = _harness_pin(ctx, "data-platform", rules_key)
    return out
